name: Deploy Wordpress Plugin

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Wordpress Plugin
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: WordPress Plugin Deploy
      uses: yukihiko-shinoda/action-deploy-wordpress-plugin@v2.0.0
      env:
        SVN_REPOSITORY_URL: ${{ secrets.SVN_URL }}
        SVN_USER_NAME: ${{ secrets.SVN_USERNAME }}
        SVN_USER_PASSWORD: ${{ secrets.SVN_PASSWORD }}
