name: Deploy Wordpress Plugin

on:
  release:
    types: [published]

jobs:
  build:
    name: Deploy Wordpress Plugin
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: WordPress Plugin Deploy
      # Switch to master whenever version 2.2.0 is released
      # https://github.com/10up/action-wordpress-plugin-deploy/milestone/7
      uses: 10up/action-wordpress-plugin-deploy@develop
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        VERSION: 3.1.11
